# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# source 'https://git.oschina.net/akuandev/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'iOSChartsDemo' do
    pod 'Charts', '~> 2.1.4'
end

