# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://git.oschina.net/akuandev/Specs.git'

target 'Paws' do
    pod 'Parse', '~> 1.7.1'
    pod 'ParseUI', '~> 1.1.3'
end

